grafana:
  adminUser: admin
  adminPassword: prom-operator
  service:
    type: ClusterIP
  persistence:
    enabled: true

prometheus:
  prometheusSpec:
    serviceMonitorSelectorNilUsesHelmValues: false
