version: "3.8"

services:
  user-service:
    build:
      context: ./user-service
      dockerfile: Dockerfile
    volumes:
      - ./user-service:/usr/src/app
      - ./wait-for.sh:/usr/src/app/wait-for.sh
    working_dir: /usr/src/app
    env_file:
      - .env
    ports:
      - "5001:5001"
    command: >
      sh -c "./wait-for.sh mysql &&
             uvicorn app.main:app --reload --host=0.0.0.0 --port=5001"
    depends_on:
      mysql:
        condition: service_healthy

  book-service:
    build:
      context: ./book-service
      dockerfile: Dockerfile
    volumes:
      - ./book-service:/usr/src/app
      - ./wait-for.sh:/usr/src/app/wait-for.sh
    working_dir: /usr/src/app
    env_file:
      - .env
    ports:
      - "5002:5002"
    command: >
      sh -c "./wait-for.sh mysql &&
             uvicorn app.main:app --reload --host=0.0.0.0 --port=5002"
    depends_on:
      mysql:
        condition: service_healthy

  borrowing-service:
    build:
      context: ./borrowing-service
      dockerfile: Dockerfile
    volumes:
      - ./borrowing-service:/usr/src/app
      - ./wait-for.sh:/usr/src/app/wait-for.sh
    working_dir: /usr/src/app
    env_file:
      - .env
    ports:
      - "5003:5003"
    command: >
      sh -c "./wait-for.sh mysql && \
         export FLASK_APP=app.main:create_app && \
         export FLASK_ENV=development && \
         flask run --host=0.0.0.0 --port=5003"

    depends_on:
      mysql:
        condition: service_healthy

  mysql:
    image: mysql:8.0
    env_file:
      - .env
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./mysql-init:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 5s
      retries: 10

volumes:
  mysql_data:
