apiVersion: apps/v1
kind: Deployment
metadata:
  name: book-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: book-service
  template:
    metadata:
      labels:
        app: book-service
    spec:
      serviceAccountName: book-service-account  # 👈 Added for RBAC
      containers:
        - name: book-service
          image: book-service:latest
          imagePullPolicy: IfNotPresent
          env:
            - name: DB_USER
              valueFrom:
                configMapKeyRef:
                  name: book-service-config
                  key: db-user
            - name: DB_HOST
              value: "mysql"
            - name: DB_PORT
              valueFrom:
                configMapKeyRef:
                  name: book-service-config
                  key: db-port
            - name: DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: book-service-config
                  key: db-name
            - name: DATABASE_URL
              valueFrom:
                configMapKeyRef:
                  name: book-service-config
                  key: database-url
            - name: ALGORITHM
              valueFrom:
                configMapKeyRef:
                  name: book-service-config
                  key: algorithm
            - name: ACCESS_TOKEN_EXPIRE_MINUTES
              valueFrom:
                configMapKeyRef:
                  name: book-service-config
                  key: access-token-expire-minutes
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: book-service-secret
                  key: db-password
            - name: SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: book-service-secret
                  key: secret-key
          ports:
            - containerPort: 5002
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "200m"
              memory: "256Mi"
          command: ["sh", "-c", "./wait-for.sh mysql && uvicorn app.main:app --host 0.0.0.0 --port 5002"]
