apiVersion: v1
kind: Secret
metadata:
  name: book-service-secret
type: Opaque
stringData:
  db-password: lms_pass1
  secret-key: PXzmJnRl6i0jzIvRPZd-SzIKYwRjLES06AwiJNA3sBQ
  mysql-root-password: example
