apiVersion: v1
kind: Secret
metadata:
  name: user-service-secret
type: Opaque
stringData:
  db-password: lms_pass1
  secret-key: PXzmJnRl6i0jzIvRPZd-SzIKYwRjLES06AwiJNA3sBQ
  jwt-secret: your_super_secret_key
  database-url: mysql+mysqlconnector://lms_user1:lms_pass1@mysql:3306/lms_users
